apiVersion: v1
kind: Pod
metadata:
  name: postgres-client-v1
  namespace: confluent
spec:
  containers:
  - name: postgres-client-v1
    image: gcr.io/rental-dev/postgres-client:14.10-alpine3.18
    # Just spin & wait forever
    command: [ "sleep" ]
    args: [ "infinity" ]
